
services:
  # Base de données MySQL
  mysql:
    image: mysql:8.0
    container_name: chatrestaurant_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ChatRestaurant
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatrestaurant_network

  # Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatrestaurant_backend
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=chatuser
      - DB_PASSWORD=chatpassword
      - DB_NAME=ChatRestaurant
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - chatrestaurant_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatrestaurant_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # éviter de monter node_modules de l’hôte
    networks:
      - chatrestaurant_network
    environment:
      - NODE_ENV=development


  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatrestaurant_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: chatuser
      PMA_PASSWORD: chatpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - chatrestaurant_network

volumes:
  mysql_data:

networks:
  chatrestaurant_network:
    driver: bridge
